apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: z2tanl7zk-go
  janus-idp.io/tekton: z2tanl7zk-go
  backstage.io/kubernetes-id: z2tanl7zk-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: z2tanl7zk-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
